apiVersion: build.knative.dev/v1alpha1
kind: BuildTemplate
metadata:
  name: java-buildah
spec:
  parameters:
    - name: JAVA_APP_BUILDER_IMAGE
      description: The builder image used to build the java application
      default: "quay.io/workspace7/java-builder"
    - name: JAVA_APP_NAME
      description: The jar file name of the build artifact
    - name: BUILDER_IMAGE
      description: The builder image to build the OCI container 
      default: quay.io/workspace7/buildah
    - name: IMAGE_NAME
      description: The name of the image to build and push, you can use %a for artifact id from pom.xml and %v for version from pom.xml and %g for group from pom.xml
      default: "dev.local/%a:%v"
    - name: CONTEXT_DIR
      description: The directory containing the app, relative to the source repository root
      default: .
    - name: CACHE
      description: The name of the volume for caching Maven artifacts
      default: empty-dir-volume
    - name: BUILDAH_SCRIPT
      description: The name of buildah script that will be used to build OCI container
      default: buildah.sh

  steps:
    - name: build-app
      image: ${JAVA_APP_BUILDER_IMAGE}
      args:
        - clean
        - package
        - -Pnative
      volumeMounts:
        - name: ${CACHE}
          mountPath: /opt/jboss
          subpath: .m2
    - name: build-container-push
      image: ${BUILDER_IMAGE}
      workingDir: /workspace/${CONTEXT_DIR}
      args: ["bash","-c","/workspace/${CONTEXT_DIR}/${BUILDAH_SCRIPT}"]
      env:
      - name: CONTEXT_DIR
        value: "${CONTEXT_DIR}"
      - name: IMAGE_NAME
        value: "${IMAGE_NAME}"
      - name: JAVA_APP_NAME
        value: "${JAVA_APP_NAME}"
      - name: POD_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace

  volumes:
    - name: empty-dir-volume
      emptyDir: {}
